version: '3.8'
services:
  postgres_db:
    image: postgres:15
    container_name: task_manager_db
    restart: always
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: task_manager
    volumes:
      - pg_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: task_manager_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: admin      
    ports:
      - "8080:80" 
    depends_on:
      - postgres_db 
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  pgadmin_data: 